[build]
  publish = "public"
  command = "ssh-keyscan github.com >> ~/.ssh/known_hosts hugo"

[context.production.environment]
  HUGO_VERSION = "0.50"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
